### PR TITLE
Adds custom nodeserver_config standard.

### PR DESCRIPTION
**Pull request by Einstein42**
Adds YAML support for new poly.nodeserver_config.

Allows both reading, and writing back to custom config file using Polyglot's new standard of YAML. Documentation link in Issue #49 notes.

You can specify the "configfile": "filename.yaml" in the server.json or it will automatically look for "config.yaml" in the node_server root directory.

### CODE REVIEW

**Comment by mkohanim** [comment]
Hello everyone,

Thanks so very much for all the feedback and suggestions. I do not know much about YAML. Based on a quick review, it seems that its most important feature is human readability. My main question is: what happens to all those node servers already working? Do they have to be migrated?

With kind regards,
Michel

**Comment by Einstein42** [comment]
I made this feature backwards compatible, so anything the node server authors are currently doing will continue to work. We just felt it was in the best interest to standardize this moving forward as even we did it differently. Moving forward the YAML way will be "how it should be done", but not required.

**Comment by mkohanim** [comment]
Thanks James!
Do we have a document describing the YAML structure?

With kind regards,

**Comment by Einstein42** [comment]
This is the one that I use.
[http://yaml.org/spec/1.1/#id857168](http://yaml.org/spec/1.1/#id857168)

**Pull request merged**
